//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GIROS
    {
        public CT_GIROS()
        {
            this.T_CONTRATOS = new HashSet<T_CONTRATOS>();
        }
    
        public long ID_GIRO { get; set; }
        public string CLAVE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<T_CONTRATOS> T_CONTRATOS { get; set; }
    }
}
