//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_RANGO_TARIFA
    {
        public long ID_RANGO_TARIFA { get; set; }
        public int RANGO { get; set; }
        public long LIMITE_SUPERIOR { get; set; }
        public double COSTO_METRO_CUBICO { get; set; }
    }
}
