//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TARIFAS
    {
        public long ID_TARIFA { get; set; }
        public long USO { get; set; }
        public long CLASE { get; set; }
        public long SERVICIO { get; set; }
        public long RANGO { get; set; }
        public double IMPORTE_CONSUMO_m3 { get; set; }
        public double CONSUMO_m3 { get; set; }
        public double IMPORTE { get; set; }
        public double IMPORTE_DRENAJE { get; set; }
    }
}
