//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIFAYCOEntities : DbContext
    {
        public SIFAYCOEntities()
            : base("name=SIFAYCOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_ANOMALIAS> CT_ANOMALIAS { get; set; }
        public DbSet<CT_CAJAS> CT_CAJAS { get; set; }
        public DbSet<CT_GIROS> CT_GIROS { get; set; }
        public DbSet<CT_INSTITUCIONES_BANCARIAS> CT_INSTITUCIONES_BANCARIAS { get; set; }
        public DbSet<CT_METODOS_DE_PAGO> CT_METODOS_DE_PAGO { get; set; }
        public DbSet<CT_RANGO_TARIFA> CT_RANGO_TARIFA { get; set; }
        public DbSet<CT_STATUS_SERVICIO> CT_STATUS_SERVICIO { get; set; }
        public DbSet<CT_TARIFAS> CT_TARIFAS { get; set; }
        public DbSet<CT_TIPOS_OTROS_CARGOS> CT_TIPOS_OTROS_CARGOS { get; set; }
        public DbSet<CT_TOMAS> CT_TOMAS { get; set; }
        public DbSet<CT_USO> CT_USO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T_CONFIGURACION_GENERAL> T_CONFIGURACION_GENERAL { get; set; }
        public DbSet<T_CONTRATOS> T_CONTRATOS { get; set; }
        public DbSet<T_DRENAJE> T_DRENAJE { get; set; }
        public DbSet<T_EMPLEADOS> T_EMPLEADOS { get; set; }
        public DbSet<T_FRECUENCIA> T_FRECUENCIA { get; set; }
        public DbSet<T_LECTURAS_MEDIDOR> T_LECTURAS_MEDIDOR { get; set; }
        public DbSet<T_OTROS_CARGOS> T_OTROS_CARGOS { get; set; }
        public DbSet<T_PAGOS> T_PAGOS { get; set; }
        public DbSet<T_UNION_PAGO_LECTURA_MEDIDOR> T_UNION_PAGO_LECTURA_MEDIDOR { get; set; }
        public DbSet<T_UNION_PAGO_OTRO_CARGO> T_UNION_PAGO_OTRO_CARGO { get; set; }
        public DbSet<T_USUARIO_SERVICIO> T_USUARIO_SERVICIO { get; set; }
        public DbSet<V_DRENAJE> V_DRENAJE { get; set; }
        public DbSet<V_LECTURAS_MEDIDOR> V_LECTURAS_MEDIDOR { get; set; }
        public DbSet<V_OTROS_CARGOS> V_OTROS_CARGOS { get; set; }
        public DbSet<V_TARIFAS> V_TARIFAS { get; set; }
        public DbSet<V_UNION_PAGO_LECTURA_MEDIDOR> V_UNION_PAGO_LECTURA_MEDIDOR { get; set; }
        public DbSet<V_UNION_PAGO_OTRO_CARGO> V_UNION_PAGO_OTRO_CARGO { get; set; }
    }
}
