//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIGURACION_GENERAL
    {
        public int ID_PROPIEDAD { get; set; }
        public string DESCRIPCION_DE_PROPIEDAD { get; set; }
        public string NOMBRE_CLAVE_DE_PROPIEDAD { get; set; }
        public string VALOR { get; set; }
    }
}
