//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONTRATOS
    {
        public T_CONTRATOS()
        {
            this.T_DRENAJE = new HashSet<T_DRENAJE>();
            this.T_OTROS_CARGOS = new HashSet<T_OTROS_CARGOS>();
            this.T_LECTURAS_MEDIDOR = new HashSet<T_LECTURAS_MEDIDOR>();
        }
    
        public long ID_CONTRATO { get; set; }
        public long ID_USUARIO_SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_INSPECCION { get; set; }
        public Nullable<System.DateTime> FECHA_CONTRATO { get; set; }
        public Nullable<long> NUMERO_CONTRATO { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public Nullable<int> CODIGO_POSTAL { get; set; }
        public Nullable<int> SECTOR { get; set; }
        public string MANZANA { get; set; }
        public Nullable<int> LOTE { get; set; }
        public Nullable<int> RUTA { get; set; }
        public string PROGRESIVO { get; set; }
        public Nullable<long> REFERENCIA { get; set; }
        public Nullable<int> USO { get; set; }
        public Nullable<int> CLASE { get; set; }
        public Nullable<int> SERVICIO { get; set; }
        public Nullable<int> NUMERO_HABITANTES { get; set; }
        public long ID_GIRO { get; set; }
        public long ID_TIPO_DE_TOMA { get; set; }
        public Nullable<double> COSTO_TOMA { get; set; }
        public Nullable<long> MEDIDOR_NUMERO { get; set; }
        public Nullable<double> MEDIDOR_DIAMETRO_pulg { get; set; }
        public string MEDIDOR_MARCA { get; set; }
        public string MEDIDOR_MODELO { get; set; }
        public Nullable<int> MEDIDOR_INDICADORES { get; set; }
        public Nullable<long> ID_STATUS_SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION_REGISTRO { get; set; }
    
        public virtual CT_GIROS CT_GIROS { get; set; }
        public virtual CT_TOMAS CT_TOMAS { get; set; }
        public virtual T_USUARIO_SERVICIO T_USUARIO_SERVICIO { get; set; }
        public virtual ICollection<T_DRENAJE> T_DRENAJE { get; set; }
        public virtual ICollection<T_OTROS_CARGOS> T_OTROS_CARGOS { get; set; }
        public virtual ICollection<T_LECTURAS_MEDIDOR> T_LECTURAS_MEDIDOR { get; set; }
    }
}
