//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FRECUENCIA
    {
        public long ID_FRECUENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public double DIAS_NATURALES { get; set; }
        public int HABILITADO { get; set; }
    }
}
