//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OTROS_CARGOS
    {
        public T_OTROS_CARGOS()
        {
            this.T_UNION_PAGO_OTRO_CARGO = new HashSet<T_UNION_PAGO_OTRO_CARGO>();
        }
    
        public long ID_OTRO_CARGO { get; set; }
        public long ID_TIPO_OTRO_CARGO { get; set; }
        public long ID_EMPLEADO_CAPTURA { get; set; }
        public long ID_EMPLEADO_REPORTA { get; set; }
        public long ID_CONTRATO { get; set; }
        public long ID_ANOMALIA { get; set; }
        public System.DateTime FECHA_CAPTURA { get; set; }
        public double IMPORTE_OTRO_CARGO { get; set; }
        public double IMPORTE_OTRO_CARGO_AJUSTADO { get; set; }
        public double PORCENTAJE_DESCUENTO { get; set; }
        public System.DateTime FECHA_ALTA_REGISTRO { get; set; }
        public System.DateTime FECHA_MODIFICACION_REGISTRO { get; set; }
    
        public virtual CT_ANOMALIAS CT_ANOMALIAS { get; set; }
        public virtual CT_TIPOS_OTROS_CARGOS CT_TIPOS_OTROS_CARGOS { get; set; }
        public virtual T_CONTRATOS T_CONTRATOS { get; set; }
        public virtual T_EMPLEADOS T_EMPLEADOS { get; set; }
        public virtual T_EMPLEADOS T_EMPLEADOS1 { get; set; }
        public virtual ICollection<T_UNION_PAGO_OTRO_CARGO> T_UNION_PAGO_OTRO_CARGO { get; set; }
    }
}
