//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UNION_PAGO_OTRO_CARGO
    {
        public long ID_UNION_PAGO_OTRO_CARGO { get; set; }
        public long ID_PAGO { get; set; }
        public long ID_OTRO_CARGO { get; set; }
        public double IMPORTE_PAGADO { get; set; }
        public System.DateTime FECHA_ALTA_REGISTRO { get; set; }
        public System.DateTime FECHA_MODIFICACION_REGISTRO { get; set; }
    
        public virtual T_OTROS_CARGOS T_OTROS_CARGOS { get; set; }
        public virtual T_PAGOS T_PAGOS { get; set; }
    }
}
