//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifayco
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USUARIO_SERVICIO
    {
        public T_USUARIO_SERVICIO()
        {
            this.T_CONTRATOS = new HashSet<T_CONTRATOS>();
        }
    
        public long ID_USUARIO_SERVICIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string CALLE { get; set; }
        public Nullable<int> NUMERO_EXTERIOR { get; set; }
        public Nullable<int> NUMERO_INTERIOR { get; set; }
        public string COLONIA { get; set; }
        public int CODIGO_POSTAL { get; set; }
        public string REFERENCIA { get; set; }
    
        public virtual ICollection<T_CONTRATOS> T_CONTRATOS { get; set; }
    }
}
